### ISSUE TITLE
The same file can be uploaded multiple times

### ISSUE THREAD

**Issue by mt-empty** [Visual-Testing-for-Android-Apps/web#26]
- [x] **I have checked that this bug has not yet been reported by someone else**
- [x] **I have specified the branch** : develop
- [x] **I have specified my browser** :  Firefox

### Steps to reproduce

1. pick and image or video file.
2. upload this file multiple times

### Expected behaviour

The app should not accept the file, it should display a notification that the file was upload 

### Actual behaviour

the app accepts the file.

**Comment by mt-empty** [comment]
Furthermore, the drag and drop showed display a different image if the file type is not accepted by our application.
For example try to drag and drop a png image.

**Comment by idomo1** [comment]
Fixed by https://github.com/Visual-Testing-for-Android-Apps/web/pull/42
