### ISSUE TITLE
Wrong alert is displayed when uploading invalid file types

### ISSUE THREAD

**Issue by Akshith-Patil** [Visual-Testing-for-Android-Apps/web#57]
- [x] **I have checked that this bug has not yet been reported by someone else**
- [x] **I have specified the branch** : develop
- [x] **I have specified my browser** : Chrome/Opera

### Screenshots (if any)

..
![Invalid Upload file bug](https://user-images.githubusercontent.com/81655881/133867806-d9f12b75-49c3-47b0-b075-b9a6abc0c101.PNG)
.

### Steps to reproduce
Upload an invalid file type 
...

### Expected behaviour
Alert with the following message should appear: "You are trying to upload invalid file types"
...

### Actual behaviour
Duplicate file alert is displayed
...

**Comment by leanne-b** [comment]
It also occurs when you upload multiple times with different files each time to exceed the file limit
